### ISSUE TITLE
Incorrect resource title

### ISSUE THREAD

**Issue by SnowballSH** [imsaptarshi/DesignJunction#1]
According to https://www.awwwards.com/, their brand is "Awwwards" (3 w's) while DesignJunction shows 
![image](https://user-images.githubusercontent.com/66022611/131203761-1ce857c1-bbf0-41c0-8765-2dc26a78ac30.png)
"Awwwwards" (4 w's).

Probably just a simple UPDATE statement in the DB.

**Comment by imsaptarshi** [comment]
> According to https://www.awwwards.com/, their brand is "Awwwards" (3 w's) while DesignJunction shows
> ![image](https://user-images.githubusercontent.com/66022611/131203761-1ce857c1-bbf0-41c0-8765-2dc26a78ac30.png)
> "Awwwwards" (4 w's).
> 
> Probably just a simple UPDATE statement in the DB.

Thanks for the concern snow! We've changed it.

**Comment by SnowballSH** [comment]
:smilecat:
